# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$env = <<SCRIPT
echo "export GOPATH=/home/vagrant/go" >> ~/.profile
echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.profile
SCRIPT

$install = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive
apt-get update > /dev/null
echo "------------ Installing Open vSwitch ------------"
apt-get install -q -y openvswitch-switch
sudo ovs-vsctl add-br docker0-ovs
echo "------------ Installing Goplane ------------"
apt-get install -q -y git
curl -sSL https://get.docker.com/ubuntu/ | sh > /dev/null
wget --quiet https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
tar axf go1.4.2.linux-amd64.tar.gz
mv go /usr/local/go
mkdir -p /home/vagrant/go/src/github.com/osrg
cd /home/vagrant/go/src/github.com/osrg
git clone https://github.com/osrg/gobgp
cd gobgp
git checkout evpn
cd ../
git clone https://github.com/osrg/goplane
cd goplane/ovs/goaddmac
go get -v && go build
ln -s `pwd`/goaddmac /usr/local/bin/goaddmac
cd ../../goplaned
go get -v && go build
ln -s `pwd`/goplaned /usr/local/bin/goplaned
ln -s /vagrant/docker_goplane.sh /usr/local/bin/docker_goplane
ln -s /vagrant/generate_config.sh /usr/local/bin/generate_config
SCRIPT

n_vms = 3

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ips = ""
  n_vms.times do |n|
    ips += "10.9.9.#{n+2}"
    ips += " "
  end

  n_vms.times do |n|
    config.vm.define "goplane#{n+1}" do |ubuntu|
      ubuntu.vm.box = "ubuntu/trusty64"
      ip = "10.9.9.#{n+2}"
      index = n+1
      ubuntu.vm.hostname = "goplane#{index}"
      ubuntu.vm.network :private_network, ip: "#{ip}", virtualbox__intnet: "goplane_intnet"
      ubuntu.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      end

      ubuntu.vm.provision :shell, inline: $env
      ubuntu.vm.provision :shell, inline: $install

      n_vms.times do |m|
        if n != m
          ubuntu.vm.provision :shell, inline: "ovs-vsctl add-port docker0-ovs \"vxlan-10.9.9.#{m+2}\" -- set interface \"vxlan-10.9.9.#{m+2}\" type=vxlan options:remote_ip=10.9.9.#{m+2}"
        end
      end

      ubuntu.vm.provision :shell, inline: "generate_config #{n+1} #{ips} > goplaned.conf"
    end
  end
end
